<a href="https://colab.research.google.com/github/konrado10/NaukaGIT/blob/main/Zad125.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Zad 1

In [1]:
!pip install --upgrade scikit-learn

     |████████████████████████████████| 6.8MB 5.5MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [3]:
df = df_raw.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [5]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df.weight = df.weight.astype('float')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [8]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [9]:
 df.describe(include = 'category')

size color  gender bought
count     5     5       5      5
unique    3     3       2      2
top       M   red  female    yes
freq      2     2       3      3

### LabelEncoder

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()
le.fit(df.bought)
le.transform(df.bought)

array([1, 0, 1, 0, 1])

In [12]:
le.fit_transform(df.bought)

array([1, 0, 1, 0, 1])

In [13]:
le.classes_

array(['no', 'yes'], dtype=object)

In [14]:
df.bought = le.fit_transform(df.bought)
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [24]:
df.bought = le.inverse_transform(df.bought)

### OneHotEncoder

In [19]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse = False)
encoder.fit(df[['size']])

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [20]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [21]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [22]:
encoder = OneHotEncoder(sparse=False, drop = 'first')
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [25]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

## Zad 2

### pd.get_dummies()

In [26]:
pd.get_dummies(df)

price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  199.0   500.0       0  ...            0          0           1
1   89.0   450.0       1  ...            1          1           0
2   99.0   300.0       0  ...            1          0           1
3  129.0   380.0       1  ...            0          1           0
4   79.0   410.0       0  ...            0          0           1

[5 rows x 12 columns]

In [27]:
pd.get_dummies(df, drop_first=True)

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  199.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]

In [28]:
pd.get_dummies(df, drop_first=True, prefix='new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [30]:
pd.get_dummies(df, drop_first=True, prefix='new', prefix_sep='-')

price  weight  new-M  new-XL  new-green  new-red  new-male  new-yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [32]:
pd.get_dummies(df, drop_first=True, prefix='new', prefix_sep='-', columns = ['size'])

color  gender  price  weight bought  new-M  new-XL
0    red  female  199.0   500.0    yes      0       1
1  green    male   89.0   450.0     no      0       0
2   blue    male   99.0   300.0    yes      1       0
3  green  female  129.0   380.0     no      0       0
4    red  female   79.0   410.0    yes      1       0

## Zad 3

### StandardScaler - standaryzacja

std() - pandas nieobciążony \
std() - numpy obciążonmy

In [33]:
def standardize(x):
    return (x - x.mean())/ x.std()

standardize(df.price)

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [34]:
from sklearn.preprocessing import scale

scale(df.price)

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [37]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

In [38]:
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [39]:
le = LabelEncoder()

df.bought = le.fit_transform(df.bought)

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(df, drop_first=True)
df

price    weight  bought  ...  color_green  color_red  gender_male
0  1.845062  1.366002       1  ...            0          1            0
1 -0.691898  0.623610       0  ...            1          0            1
2 -0.461266 -1.603567       1  ...            0          0            1
3  0.230633 -0.415740       0  ...            1          0            0
4 -0.922531  0.029696       1  ...            0          1            0

[5 rows x 8 columns]