<a href="https://colab.research.google.com/github/konrado10/NaukaGIT/blob/master/Zad104.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy


Instalacja numpy:
!pip install numpy

import numpy

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [4]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

1D Array

In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [12]:
np.array([1.3,2.3,3,3])

array([1.3, 2.3, 3. , 3. ])

In [13]:
  x.dtype

dtype('int64')

2D array

In [17]:
y = np.array([[1,2], [3,4]])

In [18]:
y.ndim

2

In [19]:
y.shape

(2, 2)

3D array

In [20]:
x = np.array(
    [[[4,2,1],
      [3,1,2]],
     
     [[4,1,3],
      [4,2,1]],
     
     [[1,23,5],
      [5,6,8]]]
)

In [21]:
print(x)

[[[ 4  2  1]
  [ 3  1  2]]

 [[ 4  1  3]
  [ 4  2  1]]

 [[ 1 23  5]
  [ 5  6  8]]]


In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

typy danych

In [25]:
a = np.array([1,2,3], dtype='float')

In [26]:
a.dtype

dtype('float64')

In [27]:
b = np.array([1.2,3,5.2], dtype = 'int')

In [28]:
b.dtype

dtype('int64')

In [29]:
b

array([1, 3, 5])

In [30]:
c = np.array([True, False])
c.dtype

dtype('bool')

In [31]:
d = np.array([1,50,781], dtype = 'int8')

In [32]:
d.dtype

dtype('int8')

Tworzenie tablic

In [35]:
np.zeros(shape=(4,10, 2), dtype = 'int')

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [36]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [40]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [41]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [43]:
np.linspace(start=0, stop=1, num =11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [45]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [49]:
A = np.array([3,1,3,2])
B = np.array([3,2,-2,-9])

In [50]:
A+B

array([ 6,  3,  1, -7])

In [51]:
A-B

array([ 0, -1,  5, 11])

In [52]:
A*B

array([  9,   2,  -6, -18])

In [53]:
A/B

array([ 1.        ,  0.5       , -1.5       , -0.22222222])

In [54]:
A+3

array([6, 4, 6, 5])

In [55]:
2*A

array([6, 2, 6, 4])

In [56]:
A+3*B

array([ 12,   7,  -3, -25])

In [57]:
np.add(A,B)

array([ 6,  3,  1, -7])

In [58]:
np.subtract(A,B)

array([ 0, -1,  5, 11])

In [60]:
np.multiply(A,B)

array([  9,   2,  -6, -18])

In [61]:
np.divide(A,B)

array([ 1.        ,  0.5       , -1.5       , -0.22222222])

In [63]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1, 2]])

In [64]:
X*Y

array([[6, 0],
       [2, 0]])

In [65]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [66]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [67]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [68]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [69]:
np.random.seed(0)

In [70]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [71]:
np.random.randn(10,4)

array([[ 0.14404357,  1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028]])

In [72]:
np.random.rand()

0.15896958364551972

In [73]:
np.random.rand(10,2)

array([[0.11037514, 0.65632959],
       [0.13818295, 0.19658236],
       [0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318]])

In [74]:
np.random.randint(10)

3

In [75]:
 np.random.randint(low=10, high = 101, size = 10)

array([77, 92, 56, 30, 91, 60, 37, 24, 51, 68])

In [76]:
np.random.choice([1,2,3,4,5])

2

In [77]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.random.shuffle(data)

In [79]:
data

array([1, 9, 8, 5, 2, 7, 0, 3, 6, 4])

In [80]:
np.exp(1)

2.718281828459045

In [81]:
np.sqrt(9)

3.0

In [82]:
np.all([2,3,1])

True

In [85]:
np.any([0,0,0])

False

In [88]:
A= np.random.rand(5)
A

array([0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644])

In [89]:
np.argmax(A)

3

In [90]:
np.argmin(A)

1

In [91]:
np.argsort(A)

array([1, 4, 0, 2, 3])

In [92]:
np.max(A)

0.7037372792899163

In [94]:
np.min(A)

0.14644176272911225

In [95]:
np.mean(A)

0.4156163955478408

In [96]:
np.median(A)

0.36980809274834003

In [97]:
np.std(A)

0.19872001180237212

Indesksowanie, wycinanie

In [98]:
A =np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [99]:
A[1]

1

In [100]:
A[1:5]

array([1, 2, 3, 4])

In [101]:
A[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [102]:
A[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [103]:
A[[0,2]]

array([0, 2])

In [104]:
A[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [106]:
A = A.reshape(4,5)

In [107]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [108]:
A[:,1]

array([ 1,  6, 11, 16])

In [109]:
A[1]

array([5, 6, 7, 8, 9])

In [111]:
A[2:4, 1:-1]

array([[11, 12, 13],
       [16, 17, 18]])

In [113]:
A[10:15]

array([], shape=(0, 5), dtype=int64)

In [114]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [115]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [116]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [117]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [119]:
A = np.arange(-10, 10, 0.5)

In [122]:
A = A.reshape(10,-1)

In [123]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [124]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [125]:
np.bitwise_and(A > 0, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [126]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])